"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function OwnerPage() {
  const { user, loading } = useAuth(); const router=useRouter();
  const [tab,setTab]=useState("overview"); const [stats,setStats]=useState(null); const [admins,setAdmins]=useState([]); const [channels,setChannels]=useState([]); const [settings,setSettings]=useState(null); const [activity,setActivity]=useState([]); const [msg,setMsg]=useState("");
  useEffect(()=>{if(!loading&&(!user||user.role!=="owner"))router.replace("/dashboard")},[loading,user,router]);
  async function load(){try{const [a,c,s,st,act]=await Promise.all([api.ownerAdmins(),api.ownerChannels(),api.ownerSettings(),api.systemStats(),api.activity()]);setAdmins(a);setChannels(c);setSettings(s);setStats(st);setActivity(act)}catch(e){setMsg(e.message)}}
  useEffect(()=>{if(user?.role==='owner')load()},[user]);
  if(loading||!user)return <div className="flex-1 grid place-items-center">در حال بارگذاری...</div>;
  if(user.role!=="owner")return null;
  const nav=[["overview","نمای کلی"],["admins","مدیریت ادمین‌ها"],["branding","برندینگ و تنظیمات"],["server","سرور و لاگ‌ها"],["channels","کلاس‌ها"],["security","امنیت"]];
  return <div className="mx-auto w-full max-w-7xl px-4 py-6 space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Owner / Hyper Admin</h1><p className="text-sm text-muted-foreground">مالک فنی و زیرساخت پلتفرم</p></div><Button variant="outline" onClick={()=>router.push('/admin')}>پنل عملیاتی</Button></div>{msg&&<div className="border border-destructive rounded p-3 text-destructive">{msg}</div>}<div className="grid lg:grid-cols-[230px_1fr] gap-4"><aside className="rounded-xl border p-2 h-fit">{nav.map(([id,l])=><button key={id} onClick={()=>setTab(id)} className={`block w-full text-right rounded px-3 py-2 text-sm ${tab===id?'bg-primary text-primary-foreground':'hover:bg-muted'}`}>{l}</button>)}</aside><section className="space-y-4">{tab==='overview'&&<Overview stats={stats} channels={channels}/>} {tab==='admins'&&<Admins admins={admins} reload={load}/>} {tab==='branding'&&settings&&<Branding settings={settings} reload={load}/>} {tab==='server'&&<Server stats={stats} activity={activity}/>} {tab==='channels'&&<Channels channels={channels} reload={load}/>} {tab==='security'&&<Security/>}</section></div></div>
}

function Overview({stats,channels}){return <div className="grid sm:grid-cols-3 gap-4"><Box t="کلاس‌ها" v={channels.length}/><Box t="CPU" v={stats?`${stats.cpuCount} core`:"—"}/><Box t="RAM آزاد" v={stats?`${stats.memory.freeMb} MB`:"—"}/></div>}
function Box({t,v}){return <div className="rounded-xl border p-5"><div className="text-sm text-muted-foreground">{t}</div><div className="text-2xl font-bold mt-2">{v}</div></div>}
function Admins({admins,reload}){const [u,setU]=useState('');const[p,setP]=useState('');const[msg,setMsg]=useState('');async function add(){try{await api.createAdmin(u,p);setU('');setP('');setMsg('ادمین ساخته شد');reload()}catch(e){setMsg(e.message)}}return <div className="space-y-4"><Card title="ساخت ادمین"><div className="grid md:grid-cols-2 gap-2"><Input placeholder="username" value={u} onChange={e=>setU(e.target.value)}/><Input placeholder="رمز حداقل ۸ کاراکتر" type="password" value={p} onChange={e=>setP(e.target.value)}/></div><Button className="mt-3" onClick={add}>ساخت</Button>{msg&&<p className="text-sm mt-2">{msg}</p>}</Card><Card title="ادمین‌ها"><Table headers={["username","نام","عملیات"]} rows={admins.map(a=>[a.username,a.displayName||'-',<Button key={a._id} size="sm" variant="destructive" onClick={async()=>{if(confirm('حذف شود؟')){await api.deleteAdmin(a._id);reload()}}}>حذف</Button>])}/></Card></div>}
function Branding({settings,reload}){const [f,setF]=useState(settings);const [msg,setMsg]=useState('');async function save(){try{await api.updateOwnerSettings(f);setMsg('ذخیره شد');reload()}catch(e){setMsg(e.message)}}return <Card title="برندینگ و تنظیمات پایه"><div className="grid md:grid-cols-2 gap-3"><Field label="نام سایت" value={f.siteName} onChange={v=>setF({...f,siteName:v})}/><Field label="Logo URL" value={f.logoUrl||''} onChange={v=>setF({...f,logoUrl:v})}/><Field label="Favicon URL" value={f.faviconUrl||''} onChange={v=>setF({...f,faviconUrl:v})}/><Field label="Accent color" value={f.accentColor||''} onChange={v=>setF({...f,accentColor:v})}/></div><label className="flex gap-2 items-center mt-4 text-sm"><input type="checkbox" checked={Boolean(f.allowPublicRegister)} onChange={e=>setF({...f,allowPublicRegister:e.target.checked})}/> ثبت‌نام عمومی</label><Button className="mt-4" onClick={save}>ذخیره</Button>{msg&&<p className="text-sm mt-2">{msg}</p>}</Card>}
function Server({stats,activity}){return <div className="space-y-4"><Card title="مانیتور سرور"><pre className="text-xs whitespace-pre-wrap bg-muted p-3 rounded">{JSON.stringify(stats,null,2)}</pre></Card><Card title="Login / Logout logs"><Table headers={["user","action","ip","time"]} rows={activity.slice(0,100).map(x=>[x.username,x.action,x.ip||'-',new Date(x.at).toLocaleString('fa-IR')])}/></Card></div>}
function Channels({channels,reload}){const [u,setU]=useState('');const[d,setD]=useState('');const[t,setT]=useState('');const[msg,setMsg]=useState('');async function add(){try{await api.createChannel({username:u,displayName:d||u,streamTitle:t});setMsg('کلاس ساخته شد');setU('');setD('');setT('');reload()}catch(e){setMsg(e.message)}}return <div className="space-y-4"><Card title="ساخت کلاس"><div className="grid md:grid-cols-3 gap-2"><Input placeholder="username" value={u} onChange={e=>setU(e.target.value)}/><Input placeholder="نام نمایشی" value={d} onChange={e=>setD(e.target.value)}/><Input placeholder="عنوان" value={t} onChange={e=>setT(e.target.value)}/></div><Button className="mt-3" onClick={add}>ساخت</Button>{msg&&<p className="text-sm mt-2">{msg}</p>}</Card><Card title="کلاس‌ها"><Table headers={["username","نمایش","live","managedBy"]} rows={channels.map(c=>[c.username,c.displayName||'-',c.isLive?'LIVE':'OFFLINE',c.managedBy?.username||'-'])}/></Card></div>}
function Security(){const [cur,setCur]=useState('');const [next,setNext]=useState('');const [msg,setMsg]=useState('');return <Card title="تغییر رمز Owner"><Field label="رمز فعلی" value={cur} onChange={setCur} type="password"/><Field label="رمز جدید" value={next} onChange={setNext} type="password"/><Button className="mt-3" onClick={async()=>{try{await api.changePassword(cur,next);setMsg('رمز تغییر کرد')}catch(e){setMsg(e.message)}}}>تغییر رمز</Button>{msg&&<p className="text-sm mt-2">{msg}</p>}</Card>}
function Card({title,children}){return <div className="rounded-xl border bg-card p-5"><h2 className="font-semibold mb-4">{title}</h2>{children}</div>}
function Field({label,value,onChange,type='text'}){return <label className="text-sm block mb-3">{label}<Input className="mt-1" type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Table({headers,rows}){return <div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{headers.map(h=><th key={h} className="text-right border-b p-2">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} className="border-b p-2">{c}</td>)}</tr>)}</tbody></table></div>}
