"use client";

import { useEffect, useState } from "react";
import { KeyRound, Plus, RefreshCw, ShieldCheck, Trash2, Upload, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { api } from "@/lib/api";

function Empty({ children }) { return <div className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">{children}</div>; }
function ErrorMessage({ children }) { return children ? <p className="text-sm text-destructive">{children}</p> : null; }

export function OrganizationWorkspace({ section, classes = [] }) {
  if (section === "org-settings") return <OrganizationSettings />;
  if (section === "org-admins") return <OrganizationAdmins />;
  if (section === "groups") return <StudentGroups />;
  return <OrganizationStudents classes={classes} />;
}

function OrganizationStudents({ classes }) {
  const [students, setStudents] = useState([]); const [groups, setGroups] = useState([]); const [query, setQuery] = useState(""); const [form, setForm] = useState({ username: "", password: "", name: "", externalId: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { setError(""); try { const [studentList, groupList] = await Promise.all([api.organizationStudents(query), api.studentGroups()]); setStudents(studentList); setGroups(groupList); } catch (err) { setError(err.message); } }
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [query]);
  async function create(event) { event.preventDefault(); setBusy(true); setError(""); try { await api.createOrganizationStudent(form); setForm({ username: "", password: "", name: "", externalId: "" }); setMessage("دانش‌آموز ساخته شد."); await load(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function toggle(student) { try { const status = student.status === "ACTIVE" ? "DISABLED" : "ACTIVE"; await api.updateOrganizationStudent(student.id, { status }); await load(); } catch (err) { setError(err.message); } }
  async function remove(student) { if (!window.confirm(`دانش‌آموز «${student.name}» حذف شود؟`)) return; try { await api.deleteOrganizationStudent(student.id); await load(); } catch (err) { setError(err.message); } }
  async function assign(student, classId) { if (!classId) return; try { await api.assignStudentToClass(classId, student.id); setMessage("دسترسی کلاس ثبت شد."); } catch (err) { setError(err.message); } }
  return <div className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="size-5" /> دانش‌آموزان</CardTitle></CardHeader><CardContent className="space-y-4"><form onSubmit={create} className="grid gap-3 rounded-lg border bg-muted/20 p-4 sm:grid-cols-2 lg:grid-cols-5"><Input required dir="ltr" placeholder="username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><Input required placeholder="نام دانش‌آموز" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><Input dir="ltr" placeholder="شناسه خارجی" value={form.externalId} onChange={(event) => setForm({ ...form, externalId: event.target.value })} /><Input required minLength={8} type="password" placeholder="رمز اولیه" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /><Button type="submit" disabled={busy}><Plus className="size-4" />ساخت</Button></form><div className="flex flex-wrap items-center justify-between gap-2"><Input className="max-w-sm" placeholder="جست‌وجوی نام یا شناسه" value={query} onChange={(event) => setQuery(event.target.value)} /><Button variant="outline" size="sm" onClick={() => void load()}><RefreshCw className="size-4" />تازه‌سازی</Button></div><ErrorMessage>{error}</ErrorMessage>{message && <p className="text-sm text-emerald-600">{message}</p>}{students.length ? <div className="grid gap-3 md:grid-cols-2">{students.map((student) => <div key={student.id} className="space-y-3 rounded-lg border p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-medium">{student.name}</p><p className="text-xs text-muted-foreground" dir="ltr">{student.username} · {student.externalId}</p></div><Badge variant={student.status === "ACTIVE" ? "default" : "secondary"}>{student.status === "ACTIVE" ? "فعال" : "غیرفعال"}</Badge></div><div className="flex flex-wrap gap-2"><select className="h-9 min-w-44 rounded-md border bg-background px-2 text-sm" defaultValue="" onChange={(event) => void assign(student, event.target.value)}><option value="">افزودن به کلاس</option>{classes.map((item) => <option key={item.id || item._id} value={item.id || item._id}>{item.title || item.slug}</option>)}</select><Button size="sm" variant="outline" onClick={() => void toggle(student)}>{student.status === "ACTIVE" ? "غیرفعال‌کردن" : "فعال‌کردن"}</Button><Button size="sm" variant="destructive" onClick={() => void remove(student)}><Trash2 className="size-4" />حذف</Button></div></div>)}</div> : <Empty>دانش‌آموزی ثبت نشده است.</Empty>}</CardContent></Card></div>;
}

function StudentGroups() {
  const [groups, setGroups] = useState([]); const [students, setStudents] = useState([]); const [name, setName] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { try { const [groupList, studentList] = await Promise.all([api.studentGroups(), api.organizationStudents()]); setGroups(groupList); setStudents(studentList); } catch (err) { setError(err.message); } }
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []);
  async function create(event) { event.preventDefault(); try { await api.createStudentGroup(name); setName(""); await load(); } catch (err) { setError(err.message); } }
  async function rename(group) { const next = window.prompt("نام جدید گروه", group.name); if (!next || next === group.name) return; try { await api.updateStudentGroup(group._id, next); await load(); } catch (err) { setError(err.message); } }
  async function remove(group) { if (!window.confirm(`گروه «${group.name}» حذف شود؟`)) return; try { await api.deleteStudentGroup(group._id); await load(); } catch (err) { setError(err.message); } }
  async function add(group, studentId) { if (!studentId) return; try { await api.addStudentToGroup(group._id, studentId); setMessage("دانش‌آموز به گروه اضافه شد."); await load(); } catch (err) { setError(err.message); } }
  async function drop(group, studentId) { try { await api.removeStudentFromGroup(group._id, studentId); await load(); } catch (err) { setError(err.message); } }
  return <Card><CardHeader><CardTitle>گروه‌های دانش‌آموزی</CardTitle></CardHeader><CardContent className="space-y-4"><form onSubmit={create} className="flex flex-wrap gap-2"><Input required placeholder="مثلاً Grade 10 یا Math A" value={name} onChange={(event) => setName(event.target.value)} /><Button type="submit"><Plus className="size-4" />ساخت گروه</Button></form><ErrorMessage>{error}</ErrorMessage>{message && <p className="text-sm text-emerald-600">{message}</p>}{groups.length ? <div className="grid gap-3 md:grid-cols-2">{groups.map((group) => <div key={group._id} className="space-y-3 rounded-lg border p-4"><div className="flex items-center justify-between gap-2"><p className="font-medium">{group.name}</p><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => void rename(group)}>ویرایش</Button><Button size="icon" variant="ghost" onClick={() => void remove(group)} aria-label="حذف گروه"><Trash2 className="size-4" /></Button></div></div><select className="h-9 w-full rounded-md border bg-background px-2 text-sm" defaultValue="" onChange={(event) => void add(group, event.target.value)}><option value="">افزودن دانش‌آموز</option>{students.filter((student) => !group.studentIds?.some((item) => String(item._id) === String(student.id))).map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select><div className="flex flex-wrap gap-2">{(group.studentIds || []).map((student) => <button type="button" key={student._id} className="rounded-md border px-2 py-1 text-xs" onClick={() => void drop(group, student._id)} title="حذف از گروه">{student.name || student.externalId} ×</button>)}</div></div>)}</div> : <Empty>گروهی ساخته نشده است.</Empty>}</CardContent></Card>;
}

function OrganizationAdmins() {
  const [admins, setAdmins] = useState([]); const [form, setForm] = useState({ username: "", password: "", role: "ADMIN_L1" }); const [error, setError] = useState("");
  async function load() { try { setAdmins(await api.organizationAdmins()); } catch (err) { setError(err.message); } }
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []);
  async function create(event) { event.preventDefault(); try { await api.createOrganizationAdmin(form); setForm({ username: "", password: "", role: "ADMIN_L1" }); await load(); } catch (err) { setError(err.message); } }
  async function patch(admin, payload) { try { await api.updateOrganizationAdmin(admin.id, payload); await load(); } catch (err) { setError(err.message); } }
  async function remove(admin) { if (!window.confirm(`مدیر «${admin.username}» حذف شود؟`)) return; try { await api.deleteOrganizationAdmin(admin.id); await load(); } catch (err) { setError(err.message); } }
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5" />مدیران</CardTitle></CardHeader><CardContent className="space-y-4"><form onSubmit={create} className="grid gap-2 sm:grid-cols-4"><Input required dir="ltr" placeholder="username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><Input required minLength={8} type="password" placeholder="رمز اولیه" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /><select className="h-9 rounded-md border bg-background px-2 text-sm" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="ADMIN_L1">مدیر سطح اول</option><option value="ADMIN_L2">مدیر سطح دوم</option></select><Button type="submit"><Plus className="size-4" />ساخت مدیر</Button></form><ErrorMessage>{error}</ErrorMessage>{admins.length ? <div className="space-y-2">{admins.map((admin) => <div key={admin.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border p-3 text-sm"><span><b>{admin.displayName || admin.username}</b> · <span dir="ltr">{admin.username}</span> · {admin.role}</span><div className="flex flex-wrap gap-2"><Badge variant={admin.status === "ACTIVE" ? "default" : "secondary"}>{admin.status === "ACTIVE" ? "فعال" : "غیرفعال"}</Badge><Button size="sm" variant="outline" onClick={() => void patch(admin, { status: admin.status === "ACTIVE" ? "DISABLED" : "ACTIVE" })}>{admin.status === "ACTIVE" ? "غیرفعال‌کردن" : "فعال‌کردن"}</Button><Button size="sm" variant="destructive" onClick={() => void remove(admin)}><Trash2 className="size-4" />حذف</Button></div></div>)}</div> : <Empty>مدیری ثبت نشده است.</Empty>}</CardContent></Card>;
}

function OrganizationSettings() {
  const [data, setData] = useState(null); const [file, setFile] = useState(null); const [appearance, setAppearance] = useState({}); const [guest, setGuest] = useState(false); const [passwords, setPasswords] = useState({ currentPassword: "", password: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { try { const result = await api.organizationSettings(); setData(result); setAppearance(result.organization.classAppearance || {}); setGuest(Boolean(result.organization.guestAccessDefault)); } catch (err) { setError(err.message); } }
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []);
  async function saveAppearance(event) { event.preventDefault(); try { await api.updateOrganizationSettings({ classAppearance: appearance, guestAccessDefault: guest }); setMessage("تنظیمات سازمان ذخیره شد."); } catch (err) { setError(err.message); } }
  async function upload() { if (!file) return; try { await api.uploadOrganizationLogo(file); setFile(null); await load(); setMessage("لوگوی سازمان ذخیره شد."); } catch (err) { setError(err.message); } }
  async function changePassword(event) { event.preventDefault(); try { await api.updateOrganizationSecurity(passwords); setPasswords({ currentPassword: "", password: "" }); setMessage("رمز عبور تغییر کرد."); } catch (err) { setError(err.message); } }
  if (!data) return <Card><CardContent className="p-6 text-sm text-muted-foreground">در حال دریافت تنظیمات...</CardContent></Card>;
  return <div className="space-y-4"><Card><CardHeader><CardTitle>برندینگ مجموعه</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center gap-3">{data.logoUrl ? <img src={data.logoUrl} alt="لوگوی مجموعه" className="size-16 rounded-md border object-contain" /> : <span className="text-sm text-muted-foreground">لوگوی مجموعه ثبت نشده است.</span>}<div className="flex gap-2"><Input type="file" accept="image/png" onChange={(event) => setFile(event.target.files?.[0] || null)} /><Button onClick={() => void upload()} disabled={!file}><Upload className="size-4" />آپلود</Button></div></div><p className="text-xs text-muted-foreground">نام و عنوان سامانه در این بخش قابل تغییر نیست و فقط در اختیار مالک اصلی است.</p></CardContent></Card><form onSubmit={saveAppearance}><Card><CardHeader><CardTitle>ظاهر کلاس‌ها</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">{[["preset", "Preset"], ["accentColor", "رنگ اصلی"], ["panelColor", "رنگ پنل"]].map(([key, label]) => <div key={key} className="space-y-1"><Label>{label}</Label><Input value={appearance[key] || ""} onChange={(event) => setAppearance({ ...appearance, [key]: event.target.value })} /></div>)}{[["backgroundDarkness", "تاریکی پس‌زمینه"], ["glassOpacity", "شفافیت شیشه"], ["glassBlur", "میزان blur"]].map(([key, label]) => <label key={key} className="space-y-1 text-sm"><span>{label}: {appearance[key] || 0}</span><input className="w-full" type="range" min="0" max="100" value={appearance[key] || 0} onChange={(event) => setAppearance({ ...appearance, [key]: Number(event.target.value) })} /></label>)}<label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={guest} onChange={(event) => setGuest(event.target.checked)} /> مهمان به‌صورت پیش‌فرض مجاز باشد</label><Button type="submit">ذخیره ظاهر کلاس</Button></CardContent></Card></form><form onSubmit={changePassword}><Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="size-5" />امنیت حساب</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><Input required type="password" placeholder="رمز فعلی" value={passwords.currentPassword} onChange={(event) => setPasswords({ ...passwords, currentPassword: event.target.value })} /><Input required minLength={8} type="password" placeholder="رمز جدید" value={passwords.password} onChange={(event) => setPasswords({ ...passwords, password: event.target.value })} /><Button type="submit">تغییر رمز</Button></CardContent></Card></form>{message && <p className="text-sm text-emerald-600">{message}</p>}<ErrorMessage>{error}</ErrorMessage></div>;
}
